#!/bin/bash

OC_BIN_PATH=../../bin/
OC_VERSION=$($OC_BIN_PATH/oc-version)

echo "Packaging version $OC_VERSION for Docker"

# Update manifest version to match current version
if [ "$(uname)" == "Darwin" ]; then
    sed -i '' "s/\"version\": \".*\"/\"version\": \"$OC_VERSION\"/" manifest.json
else
    sed -i 's/"version": "[^"]*"/"version": "'"$OC_VERSION"'"/' manifest.json
fi

mkdir OpenCola-Chrome-"$OC_VERSION"
cp -r *.js *.html *.css *.json images OpenCola-Chrome-"$OC_VERSION"
zip -r OpenCola-Chrome-"$OC_VERSION".zip OpenCola-Chrome-"$OC_VERSION"
rm -rf OpenCola-Chrome-"$OC_VERSION"