#!/bin/bash
# Make a "persistent" (storage is carried across test runs) node for testing.
# USAGE: make-node name port

pushd storage/persistent
rm -rf $1
mkdir $1
cp -r ../../../install/opencola/storage/* $1
pushd $1
sed -i '' "s/5795/$2/g" opencola-server.yaml
sed -i '' "s/5796/$3/g" opencola-server.yaml
sed -i '' "s/providerEnabled: false/providerEnabled: true/g" opencola-server.yaml
popd
popd


