#!/bin/bash

OC_BIN_PATH=../../bin/

OC_VERSION=$($OC_BIN_PATH/oc-version)

echo "Packaging version $OC_VERSION for MacOS"
# https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html
jpackage --input ../opencola/server/lib/ \
  --name OpenCola \
  --vendor OpenCola \
  --app-version "$OC_VERSION" \
  --main-jar "opencola-server-$OC_VERSION.jar" \
  --main-class opencola.server.ApplicationKt \
  --java-options '--enable-preview' \
  --arguments --desktop \
  --verbose \
  --type dmg \
  --icon desktop-icon.icns \
  --mac-package-name OpenCola \
  --mac-sign \
  --mac-signing-key-user-name "Developer ID Application: John Midgley (95W32CY3BR)"

  mv "OpenCola-$OC_VERSION.dmg" "OpenCola-MacOS-$OC_VERSION"
