version: '3.1'

services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: opencola
      # !!! Need to set OC_POSTGRES_PASSWORD before starting !!!
      POSTGRES_PASSWORD: ${OC_POSTGRES_PASSWORD}
    volumes:
      - ./data/var-postgres:/var/lib/postgresql/data

  # Useful for debugging, but not strictly necessary
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080