#!/bin/bash

# Check that protoc is installed
if ! [ -x "$(command -v protoc)" ]; then
    echo "protoc is not installed"
    exit 1
fi

# function to generate proto
function generate_proto() {
  echo "Generating $1"
    protoc --java_out=../java "$@"

    # Check error code
    if [ $? -ne 0 ]; then
        echo "Failed to compile $1"
        exit 1
    fi

    echo "Successfully compiled $1 to Java"
}

# Get *.proto files
proto_files=$(find . -name "*.proto")


# Generate proto files
for file in $proto_files; do
    generate_proto $file "$@"
done
