version: '3.8'

services:
  relay:
    build: .
    container_name: oc-relay
    ports:
      - "2652:2652"
    restart: unless-stopped
    environment:
      relay.security.publicKeyBase58: ${OC_SERVER_PUBLIC_KEY}
      relay.security.privateKeyBase58: ${OC_SERVER_PRIVATE_KEY}
      relay.security.rootIdBase58: ${OC_ROOT_ID}

    # Comment this section out if you want storage to be inside the docker container 
    # in ephemeral storage
    volumes:
      - type: bind
        source: ./storage
        target: /var/relay # This should match storagePath in opencola-relay.yaml
