version: '3.8'

services:
  relay:
    build: .
    container_name: oc-relay
    ports:
      - "2652:2652"
    restart: unless-stopped
    environment:
      relay.server.port: 2652
      relay.server.callLogging: false
      relay.security.publicKeyBase58: ${OC_SERVER_PUBLIC_KEY}
      relay.security.privateKeyBase58: ${OC_SERVER_PRIVATE_KEY}
      relay.security.rootIdBase58: ${OC_ROOT_ID}

# TODO: This volume should be the storage path set in opencola-relay.yaml
    volumes:
      - type: bind
        source: ./storage
        target: /var/relay
