#!/bin/bash
echo "Removing old dist"
rm -rf oc-relay
mkdir oc-relay

echo "Running gradle installDist"
pushd ../
../../gradlew installDist
popd || exit

echo "Copying distribution"
rm -rf oc-relay
cp -r ../../install/oc-relay .

echo "Done."




