#!/bin/bash
OC_BIN_PATH=../../../../bin/

OC_VERSION=$($OC_BIN_PATH/oc-version)
echo "OC Version: $OC_VERSION"

# NOTE: Must be logged into AWS ecr for this to work. Login with OC_BIN_PATH/aws/login

echo "Building oc-relay"
./install

docker build -t oc-relay-v2:"$OC_VERSION" .
docker tag oc-relay-v2:"$OC_VERSION" 147892678753.dkr.ecr.us-west-2.amazonaws.com/oc-relay-v2:"$OC_VERSION"
docker push 147892678753.dkr.ecr.us-west-2.amazonaws.com/oc-relay-v2:"$OC_VERSION"
