services:
  oc:
    build: ..
    container_name: opencola-server
    ports:
      - "5795:5795"
      - "5796:5796"
    volumes:
      - $OPENCOLA_HOME/storage:/opencola/storage
    restart: unless-stopped

