#!/bin/bash

# Check that protoc is installed
if ! [ -x "$(command -v protoc)" ]; then
    echo "protoc is not installed"
    exit 1
fi

protoc  --java_out=../../../../  model.proto

# Check error code
if [ $? -ne 0 ]; then
    echo "Failed to compile model.proto"
    exit 1
fi

echo "Successfully compiled model.proto to Java"
