#!/bin/sh
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ "$1" != "-f" ];
then
  echo "${RED}This script will delete any existing transactions, stores, indexes, etc.${NC}"
  echo "If this is your intention, use a -f flag"
  exit
fi

echo "Stopping network"
cd  ../network
docker-compose down
cd ../storage

echo "Deleting data files (leaving keys)"
rm -f *.db
rm -rf filestore
rm -rf mht-cache
rm -rf var-solr/logs
rm -rf var-solr/data/*.opencola
rm -rf test

echo "Re-starting docker"
cd ../network
docker-compose up -d
cd ../storage

