#!/bin/bash
echo "Cleaning build"
lein clean
echo "Building min"
lein fig:min
echo "Copying resources"
cd resources/public
cp cljs-out/dev-main.js ../../../opencola-server/src/main/resources/web/cljs-out/
cp *.html ../../../opencola-server/src/main/resources/web
cp -r css img ../../../opencola-server/src/main/resources/web
