#!/bin/bash
echo "Removing old dist"
rm -rf opencola
mkdir opencola

echo "Running gradle installDist"
cd ../opencola-server/server
../gradlew installDist

echo "Copying distribution"
cd ../../install/opencola
mkdir server
cp -r ../../opencola-server/server/build/install/opencola-server/* server
echo "Copying Chrome extension"
cp -r  ../../extension/chrome .

echo "Done."




