#!/bin/bash
echo "Removing old dist"
rm -rf opencola
mkdir opencola

echo "Running gradle installDist"
cd ../opencola-server
./gradlew installDist

echo "Copying distribution"
cd ../install/opencola
cp ../scripts/* .
cp ../README.txt .
mkdir server
cp -r ../../opencola-server/build/install/opencola-server/* server

echo "Copying config"
#cp ../../opencola-server/opencola-server.yaml server
mkdir oc-network
cp ../../network/docker-compose.yml oc-network

echo "Copying resources"
mkdir server/resources
cp -r ../../opencola-server/resources/* server/resources/

echo "Copying Chrome extension"
cp -r  ../../extension/chrome .

if [ -d "storage" ]; 
then
  echo "Storage already exists" 
else
  echo "Creating storage"
  mkdir -p storage/cert
  cp ../../storage/opencola-server.yaml storage/
  cp ../../storage/cert/gen-ssl-cert storage/cert
  cp ../../storage/cert/install-cert storage/cert
  cp ../../storage/cert/install-cert.bat storage/cert
fi
echo "Done."




