#!/bin/bash

OC_BIN_PATH=../bin/
OC_VERSION=$($OC_BIN_PATH/oc-version)

echo "Packaging version $OC_VERSION for Docker and Chrome"

# Update manifest version to match current version
sed -i 's/"version": "[^"]*"/"version": "'"$OC_VERSION"'"/' ../extension/chrome/manifest.json

./install
mkdir OpenCola-Docker-"$OC_VERSION"
cp -r Dockerfile opencola OpenCola-Docker-"$OC_VERSION"
pushd OpenCola-Docker-"$OC_VERSION"
mkdir mac
cp ../mac/docker-compose.yml ../mac/start ../mac/stop mac
mkdir windows
cp ../windows/docker-compose.yml ../windows/start.ps1 ../windows/stop.ps1 windows
mkdir linux
cp ../linux/docker-compose.yml ../linux/start ../linux/stop linux
popd
zip -r OpenCola-Docker-"$OC_VERSION".zip OpenCola-Docker-"$OC_VERSION"
rm -rf OpenCola-Docker-"$OC_VERSION"
