#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: $0 archive-name"
  exit 1
fi

echo "Creating dmg"
jpackage --input opencola/server/lib/ \
  --resource-dir opencola/server/resources/ \
  --name OpenCola \
  --main-jar opencola-server-1.0-SNAPSHOT.jar \
  --main-class opencola.server.ApplicationKt \
  --type dmg \
  --java-options '--enable-preview' \
  --verbose