#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: $0 archive-name"
  exit 1
fi

echo "Packaging for MacOS"
jpackage --input opencola/server/lib/ \
  --name OpenCola \
  --main-jar opencola-server-1.0-SNAPSHOT.jar \
  --main-class opencola.server.ApplicationKt \
  --type dmg \
  --icon icons/desktop-icon.icns \
  --java-options '--enable-preview' \
  --arguments --desktop \
  --verbose

  # --resource-dir opencola/server/resources/ \
