#!/bin/bash

OC_BIN_PATH=../../bin/
OC_VERSION=$($OC_BIN_PATH/oc-version)

echo "Packaging version $OC_VERSION for Linux"

rm -rf opencola

# https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html
jpackage --input ../opencola/server/lib/ \
  --name opencola \
  --vendor OpenCola \
  --app-version "$OC_VERSION" \
  --main-jar "opencola-server-$OC_VERSION.jar" \
  --main-class opencola.server.ApplicationKt \
  --java-options '--enable-preview' \
  --arguments --desktop \
  --verbose \
  --type app-image \
  --icon pull-tab.png

tar -cvzf "OpenCola-Linux-$OC_VERSION.tgz" opencola
