// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package io.opencola.security.protobuf;

public final class Security {
  private Security() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code io.opencola.security.protobuf.SignatureAlgorithm}
   */
  public enum SignatureAlgorithm
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SHA3_256_WITH_ECDSA = 0;</code>
     */
    SHA3_256_WITH_ECDSA(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SHA3_256_WITH_ECDSA = 0;</code>
     */
    public static final int SHA3_256_WITH_ECDSA_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SignatureAlgorithm valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SignatureAlgorithm forNumber(int value) {
      switch (value) {
        case 0: return SHA3_256_WITH_ECDSA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SignatureAlgorithm>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SignatureAlgorithm> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SignatureAlgorithm>() {
            public SignatureAlgorithm findValueByNumber(int number) {
              return SignatureAlgorithm.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.opencola.security.protobuf.Security.getDescriptor().getEnumTypes().get(0);
    }

    private static final SignatureAlgorithm[] VALUES = values();

    public static SignatureAlgorithm valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SignatureAlgorithm(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.opencola.security.protobuf.SignatureAlgorithm)
  }

  /**
   * Protobuf enum {@code io.opencola.security.protobuf.EncryptionTransformation}
   */
  public enum EncryptionTransformation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ECIES_WITH_AES_CBC = 0;</code>
     */
    ECIES_WITH_AES_CBC(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ECIES_WITH_AES_CBC = 0;</code>
     */
    public static final int ECIES_WITH_AES_CBC_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EncryptionTransformation valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EncryptionTransformation forNumber(int value) {
      switch (value) {
        case 0: return ECIES_WITH_AES_CBC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EncryptionTransformation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EncryptionTransformation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EncryptionTransformation>() {
            public EncryptionTransformation findValueByNumber(int number) {
              return EncryptionTransformation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.opencola.security.protobuf.Security.getDescriptor().getEnumTypes().get(1);
    }

    private static final EncryptionTransformation[] VALUES = values();

    public static EncryptionTransformation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EncryptionTransformation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.opencola.security.protobuf.EncryptionTransformation)
  }

  public interface PublicKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.opencola.security.protobuf.PublicKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes encoded = 1;</code>
     * @return The encoded.
     */
    com.google.protobuf.ByteString getEncoded();
  }
  /**
   * Protobuf type {@code io.opencola.security.protobuf.PublicKey}
   */
  public static final class PublicKey extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.opencola.security.protobuf.PublicKey)
      PublicKeyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PublicKey.newBuilder() to construct.
    private PublicKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PublicKey() {
      encoded_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PublicKey();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PublicKey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              encoded_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_PublicKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_PublicKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opencola.security.protobuf.Security.PublicKey.class, io.opencola.security.protobuf.Security.PublicKey.Builder.class);
    }

    public static final int ENCODED_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encoded_;
    /**
     * <code>bytes encoded = 1;</code>
     * @return The encoded.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncoded() {
      return encoded_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!encoded_.isEmpty()) {
        output.writeBytes(1, encoded_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!encoded_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, encoded_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.opencola.security.protobuf.Security.PublicKey)) {
        return super.equals(obj);
      }
      io.opencola.security.protobuf.Security.PublicKey other = (io.opencola.security.protobuf.Security.PublicKey) obj;

      if (!getEncoded()
          .equals(other.getEncoded())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENCODED_FIELD_NUMBER;
      hash = (53 * hash) + getEncoded().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.PublicKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.opencola.security.protobuf.Security.PublicKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.opencola.security.protobuf.PublicKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.opencola.security.protobuf.PublicKey)
        io.opencola.security.protobuf.Security.PublicKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_PublicKey_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_PublicKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.opencola.security.protobuf.Security.PublicKey.class, io.opencola.security.protobuf.Security.PublicKey.Builder.class);
      }

      // Construct using io.opencola.security.protobuf.Security.PublicKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        encoded_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_PublicKey_descriptor;
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.PublicKey getDefaultInstanceForType() {
        return io.opencola.security.protobuf.Security.PublicKey.getDefaultInstance();
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.PublicKey build() {
        io.opencola.security.protobuf.Security.PublicKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.PublicKey buildPartial() {
        io.opencola.security.protobuf.Security.PublicKey result = new io.opencola.security.protobuf.Security.PublicKey(this);
        result.encoded_ = encoded_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.opencola.security.protobuf.Security.PublicKey) {
          return mergeFrom((io.opencola.security.protobuf.Security.PublicKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.opencola.security.protobuf.Security.PublicKey other) {
        if (other == io.opencola.security.protobuf.Security.PublicKey.getDefaultInstance()) return this;
        if (other.getEncoded() != com.google.protobuf.ByteString.EMPTY) {
          setEncoded(other.getEncoded());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.opencola.security.protobuf.Security.PublicKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.opencola.security.protobuf.Security.PublicKey) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString encoded_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encoded = 1;</code>
       * @return The encoded.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncoded() {
        return encoded_;
      }
      /**
       * <code>bytes encoded = 1;</code>
       * @param value The encoded to set.
       * @return This builder for chaining.
       */
      public Builder setEncoded(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encoded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encoded = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncoded() {
        
        encoded_ = getDefaultInstance().getEncoded();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.opencola.security.protobuf.PublicKey)
    }

    // @@protoc_insertion_point(class_scope:io.opencola.security.protobuf.PublicKey)
    private static final io.opencola.security.protobuf.Security.PublicKey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.opencola.security.protobuf.Security.PublicKey();
    }

    public static io.opencola.security.protobuf.Security.PublicKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PublicKey>
        PARSER = new com.google.protobuf.AbstractParser<PublicKey>() {
      @java.lang.Override
      public PublicKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PublicKey(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PublicKey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PublicKey> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.opencola.security.protobuf.Security.PublicKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.opencola.security.protobuf.Signature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.io.opencola.security.protobuf.SignatureAlgorithm algorithm = 1;</code>
     * @return The enum numeric value on the wire for algorithm.
     */
    int getAlgorithmValue();
    /**
     * <code>.io.opencola.security.protobuf.SignatureAlgorithm algorithm = 1;</code>
     * @return The algorithm.
     */
    io.opencola.security.protobuf.Security.SignatureAlgorithm getAlgorithm();

    /**
     * <code>bytes bytes = 2;</code>
     * @return The bytes.
     */
    com.google.protobuf.ByteString getBytes();
  }
  /**
   * Protobuf type {@code io.opencola.security.protobuf.Signature}
   */
  public static final class Signature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.opencola.security.protobuf.Signature)
      SignatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Signature.newBuilder() to construct.
    private Signature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Signature() {
      algorithm_ = 0;
      bytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Signature();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Signature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              algorithm_ = rawValue;
              break;
            }
            case 18: {

              bytes_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_Signature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_Signature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opencola.security.protobuf.Security.Signature.class, io.opencola.security.protobuf.Security.Signature.Builder.class);
    }

    public static final int ALGORITHM_FIELD_NUMBER = 1;
    private int algorithm_;
    /**
     * <code>.io.opencola.security.protobuf.SignatureAlgorithm algorithm = 1;</code>
     * @return The enum numeric value on the wire for algorithm.
     */
    @java.lang.Override public int getAlgorithmValue() {
      return algorithm_;
    }
    /**
     * <code>.io.opencola.security.protobuf.SignatureAlgorithm algorithm = 1;</code>
     * @return The algorithm.
     */
    @java.lang.Override public io.opencola.security.protobuf.Security.SignatureAlgorithm getAlgorithm() {
      @SuppressWarnings("deprecation")
      io.opencola.security.protobuf.Security.SignatureAlgorithm result = io.opencola.security.protobuf.Security.SignatureAlgorithm.valueOf(algorithm_);
      return result == null ? io.opencola.security.protobuf.Security.SignatureAlgorithm.UNRECOGNIZED : result;
    }

    public static final int BYTES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bytes_;
    /**
     * <code>bytes bytes = 2;</code>
     * @return The bytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (algorithm_ != io.opencola.security.protobuf.Security.SignatureAlgorithm.SHA3_256_WITH_ECDSA.getNumber()) {
        output.writeEnum(1, algorithm_);
      }
      if (!bytes_.isEmpty()) {
        output.writeBytes(2, bytes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (algorithm_ != io.opencola.security.protobuf.Security.SignatureAlgorithm.SHA3_256_WITH_ECDSA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, algorithm_);
      }
      if (!bytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.opencola.security.protobuf.Security.Signature)) {
        return super.equals(obj);
      }
      io.opencola.security.protobuf.Security.Signature other = (io.opencola.security.protobuf.Security.Signature) obj;

      if (algorithm_ != other.algorithm_) return false;
      if (!getBytes()
          .equals(other.getBytes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
      hash = (53 * hash) + algorithm_;
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.opencola.security.protobuf.Security.Signature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.Signature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.Signature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.Signature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.Signature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.Signature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.Signature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.Signature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.Signature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.Signature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.Signature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.Signature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.opencola.security.protobuf.Security.Signature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.opencola.security.protobuf.Signature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.opencola.security.protobuf.Signature)
        io.opencola.security.protobuf.Security.SignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_Signature_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_Signature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.opencola.security.protobuf.Security.Signature.class, io.opencola.security.protobuf.Security.Signature.Builder.class);
      }

      // Construct using io.opencola.security.protobuf.Security.Signature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        algorithm_ = 0;

        bytes_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_Signature_descriptor;
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.Signature getDefaultInstanceForType() {
        return io.opencola.security.protobuf.Security.Signature.getDefaultInstance();
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.Signature build() {
        io.opencola.security.protobuf.Security.Signature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.Signature buildPartial() {
        io.opencola.security.protobuf.Security.Signature result = new io.opencola.security.protobuf.Security.Signature(this);
        result.algorithm_ = algorithm_;
        result.bytes_ = bytes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.opencola.security.protobuf.Security.Signature) {
          return mergeFrom((io.opencola.security.protobuf.Security.Signature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.opencola.security.protobuf.Security.Signature other) {
        if (other == io.opencola.security.protobuf.Security.Signature.getDefaultInstance()) return this;
        if (other.algorithm_ != 0) {
          setAlgorithmValue(other.getAlgorithmValue());
        }
        if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
          setBytes(other.getBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.opencola.security.protobuf.Security.Signature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.opencola.security.protobuf.Security.Signature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int algorithm_ = 0;
      /**
       * <code>.io.opencola.security.protobuf.SignatureAlgorithm algorithm = 1;</code>
       * @return The enum numeric value on the wire for algorithm.
       */
      @java.lang.Override public int getAlgorithmValue() {
        return algorithm_;
      }
      /**
       * <code>.io.opencola.security.protobuf.SignatureAlgorithm algorithm = 1;</code>
       * @param value The enum numeric value on the wire for algorithm to set.
       * @return This builder for chaining.
       */
      public Builder setAlgorithmValue(int value) {
        
        algorithm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.io.opencola.security.protobuf.SignatureAlgorithm algorithm = 1;</code>
       * @return The algorithm.
       */
      @java.lang.Override
      public io.opencola.security.protobuf.Security.SignatureAlgorithm getAlgorithm() {
        @SuppressWarnings("deprecation")
        io.opencola.security.protobuf.Security.SignatureAlgorithm result = io.opencola.security.protobuf.Security.SignatureAlgorithm.valueOf(algorithm_);
        return result == null ? io.opencola.security.protobuf.Security.SignatureAlgorithm.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.opencola.security.protobuf.SignatureAlgorithm algorithm = 1;</code>
       * @param value The algorithm to set.
       * @return This builder for chaining.
       */
      public Builder setAlgorithm(io.opencola.security.protobuf.Security.SignatureAlgorithm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        algorithm_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.opencola.security.protobuf.SignatureAlgorithm algorithm = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlgorithm() {
        
        algorithm_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes = 2;</code>
       * @return The bytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>bytes bytes = 2;</code>
       * @param value The bytes to set.
       * @return This builder for chaining.
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytes() {
        
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.opencola.security.protobuf.Signature)
    }

    // @@protoc_insertion_point(class_scope:io.opencola.security.protobuf.Signature)
    private static final io.opencola.security.protobuf.Security.Signature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.opencola.security.protobuf.Security.Signature();
    }

    public static io.opencola.security.protobuf.Security.Signature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Signature>
        PARSER = new com.google.protobuf.AbstractParser<Signature>() {
      @java.lang.Override
      public Signature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Signature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Signature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Signature> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.opencola.security.protobuf.Security.Signature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignedBytesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.opencola.security.protobuf.SignedBytes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
     * @return Whether the signature field is set.
     */
    boolean hasSignature();
    /**
     * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
     * @return The signature.
     */
    io.opencola.security.protobuf.Security.Signature getSignature();
    /**
     * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
     */
    io.opencola.security.protobuf.Security.SignatureOrBuilder getSignatureOrBuilder();

    /**
     * <code>bytes bytes = 2;</code>
     * @return The bytes.
     */
    com.google.protobuf.ByteString getBytes();
  }
  /**
   * Protobuf type {@code io.opencola.security.protobuf.SignedBytes}
   */
  public static final class SignedBytes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.opencola.security.protobuf.SignedBytes)
      SignedBytesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignedBytes.newBuilder() to construct.
    private SignedBytes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignedBytes() {
      bytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SignedBytes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignedBytes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.opencola.security.protobuf.Security.Signature.Builder subBuilder = null;
              if (signature_ != null) {
                subBuilder = signature_.toBuilder();
              }
              signature_ = input.readMessage(io.opencola.security.protobuf.Security.Signature.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(signature_);
                signature_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              bytes_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_SignedBytes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_SignedBytes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opencola.security.protobuf.Security.SignedBytes.class, io.opencola.security.protobuf.Security.SignedBytes.Builder.class);
    }

    public static final int SIGNATURE_FIELD_NUMBER = 1;
    private io.opencola.security.protobuf.Security.Signature signature_;
    /**
     * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
     * @return Whether the signature field is set.
     */
    @java.lang.Override
    public boolean hasSignature() {
      return signature_ != null;
    }
    /**
     * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
     * @return The signature.
     */
    @java.lang.Override
    public io.opencola.security.protobuf.Security.Signature getSignature() {
      return signature_ == null ? io.opencola.security.protobuf.Security.Signature.getDefaultInstance() : signature_;
    }
    /**
     * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
     */
    @java.lang.Override
    public io.opencola.security.protobuf.Security.SignatureOrBuilder getSignatureOrBuilder() {
      return getSignature();
    }

    public static final int BYTES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bytes_;
    /**
     * <code>bytes bytes = 2;</code>
     * @return The bytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (signature_ != null) {
        output.writeMessage(1, getSignature());
      }
      if (!bytes_.isEmpty()) {
        output.writeBytes(2, bytes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (signature_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSignature());
      }
      if (!bytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.opencola.security.protobuf.Security.SignedBytes)) {
        return super.equals(obj);
      }
      io.opencola.security.protobuf.Security.SignedBytes other = (io.opencola.security.protobuf.Security.SignedBytes) obj;

      if (hasSignature() != other.hasSignature()) return false;
      if (hasSignature()) {
        if (!getSignature()
            .equals(other.getSignature())) return false;
      }
      if (!getBytes()
          .equals(other.getBytes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.SignedBytes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.opencola.security.protobuf.Security.SignedBytes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.opencola.security.protobuf.SignedBytes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.opencola.security.protobuf.SignedBytes)
        io.opencola.security.protobuf.Security.SignedBytesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_SignedBytes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_SignedBytes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.opencola.security.protobuf.Security.SignedBytes.class, io.opencola.security.protobuf.Security.SignedBytes.Builder.class);
      }

      // Construct using io.opencola.security.protobuf.Security.SignedBytes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (signatureBuilder_ == null) {
          signature_ = null;
        } else {
          signature_ = null;
          signatureBuilder_ = null;
        }
        bytes_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_SignedBytes_descriptor;
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.SignedBytes getDefaultInstanceForType() {
        return io.opencola.security.protobuf.Security.SignedBytes.getDefaultInstance();
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.SignedBytes build() {
        io.opencola.security.protobuf.Security.SignedBytes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.SignedBytes buildPartial() {
        io.opencola.security.protobuf.Security.SignedBytes result = new io.opencola.security.protobuf.Security.SignedBytes(this);
        if (signatureBuilder_ == null) {
          result.signature_ = signature_;
        } else {
          result.signature_ = signatureBuilder_.build();
        }
        result.bytes_ = bytes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.opencola.security.protobuf.Security.SignedBytes) {
          return mergeFrom((io.opencola.security.protobuf.Security.SignedBytes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.opencola.security.protobuf.Security.SignedBytes other) {
        if (other == io.opencola.security.protobuf.Security.SignedBytes.getDefaultInstance()) return this;
        if (other.hasSignature()) {
          mergeSignature(other.getSignature());
        }
        if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
          setBytes(other.getBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.opencola.security.protobuf.Security.SignedBytes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.opencola.security.protobuf.Security.SignedBytes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.opencola.security.protobuf.Security.Signature signature_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.opencola.security.protobuf.Security.Signature, io.opencola.security.protobuf.Security.Signature.Builder, io.opencola.security.protobuf.Security.SignatureOrBuilder> signatureBuilder_;
      /**
       * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
       * @return Whether the signature field is set.
       */
      public boolean hasSignature() {
        return signatureBuilder_ != null || signature_ != null;
      }
      /**
       * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
       * @return The signature.
       */
      public io.opencola.security.protobuf.Security.Signature getSignature() {
        if (signatureBuilder_ == null) {
          return signature_ == null ? io.opencola.security.protobuf.Security.Signature.getDefaultInstance() : signature_;
        } else {
          return signatureBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
       */
      public Builder setSignature(io.opencola.security.protobuf.Security.Signature value) {
        if (signatureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          signature_ = value;
          onChanged();
        } else {
          signatureBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
       */
      public Builder setSignature(
          io.opencola.security.protobuf.Security.Signature.Builder builderForValue) {
        if (signatureBuilder_ == null) {
          signature_ = builderForValue.build();
          onChanged();
        } else {
          signatureBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
       */
      public Builder mergeSignature(io.opencola.security.protobuf.Security.Signature value) {
        if (signatureBuilder_ == null) {
          if (signature_ != null) {
            signature_ =
              io.opencola.security.protobuf.Security.Signature.newBuilder(signature_).mergeFrom(value).buildPartial();
          } else {
            signature_ = value;
          }
          onChanged();
        } else {
          signatureBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
       */
      public Builder clearSignature() {
        if (signatureBuilder_ == null) {
          signature_ = null;
          onChanged();
        } else {
          signature_ = null;
          signatureBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
       */
      public io.opencola.security.protobuf.Security.Signature.Builder getSignatureBuilder() {
        
        onChanged();
        return getSignatureFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
       */
      public io.opencola.security.protobuf.Security.SignatureOrBuilder getSignatureOrBuilder() {
        if (signatureBuilder_ != null) {
          return signatureBuilder_.getMessageOrBuilder();
        } else {
          return signature_ == null ?
              io.opencola.security.protobuf.Security.Signature.getDefaultInstance() : signature_;
        }
      }
      /**
       * <code>.io.opencola.security.protobuf.Signature signature = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.opencola.security.protobuf.Security.Signature, io.opencola.security.protobuf.Security.Signature.Builder, io.opencola.security.protobuf.Security.SignatureOrBuilder> 
          getSignatureFieldBuilder() {
        if (signatureBuilder_ == null) {
          signatureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.opencola.security.protobuf.Security.Signature, io.opencola.security.protobuf.Security.Signature.Builder, io.opencola.security.protobuf.Security.SignatureOrBuilder>(
                  getSignature(),
                  getParentForChildren(),
                  isClean());
          signature_ = null;
        }
        return signatureBuilder_;
      }

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes = 2;</code>
       * @return The bytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>bytes bytes = 2;</code>
       * @param value The bytes to set.
       * @return This builder for chaining.
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytes() {
        
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.opencola.security.protobuf.SignedBytes)
    }

    // @@protoc_insertion_point(class_scope:io.opencola.security.protobuf.SignedBytes)
    private static final io.opencola.security.protobuf.Security.SignedBytes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.opencola.security.protobuf.Security.SignedBytes();
    }

    public static io.opencola.security.protobuf.Security.SignedBytes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignedBytes>
        PARSER = new com.google.protobuf.AbstractParser<SignedBytes>() {
      @java.lang.Override
      public SignedBytes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignedBytes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignedBytes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignedBytes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.opencola.security.protobuf.Security.SignedBytes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EncryptedBytesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.opencola.security.protobuf.EncryptedBytes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.io.opencola.security.protobuf.EncryptionTransformation transformation = 1;</code>
     * @return The enum numeric value on the wire for transformation.
     */
    int getTransformationValue();
    /**
     * <code>.io.opencola.security.protobuf.EncryptionTransformation transformation = 1;</code>
     * @return The transformation.
     */
    io.opencola.security.protobuf.Security.EncryptionTransformation getTransformation();

    /**
     * <code>bytes bytes = 2;</code>
     * @return The bytes.
     */
    com.google.protobuf.ByteString getBytes();
  }
  /**
   * Protobuf type {@code io.opencola.security.protobuf.EncryptedBytes}
   */
  public static final class EncryptedBytes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.opencola.security.protobuf.EncryptedBytes)
      EncryptedBytesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EncryptedBytes.newBuilder() to construct.
    private EncryptedBytes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EncryptedBytes() {
      transformation_ = 0;
      bytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EncryptedBytes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EncryptedBytes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              transformation_ = rawValue;
              break;
            }
            case 18: {

              bytes_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_EncryptedBytes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_EncryptedBytes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opencola.security.protobuf.Security.EncryptedBytes.class, io.opencola.security.protobuf.Security.EncryptedBytes.Builder.class);
    }

    public static final int TRANSFORMATION_FIELD_NUMBER = 1;
    private int transformation_;
    /**
     * <code>.io.opencola.security.protobuf.EncryptionTransformation transformation = 1;</code>
     * @return The enum numeric value on the wire for transformation.
     */
    @java.lang.Override public int getTransformationValue() {
      return transformation_;
    }
    /**
     * <code>.io.opencola.security.protobuf.EncryptionTransformation transformation = 1;</code>
     * @return The transformation.
     */
    @java.lang.Override public io.opencola.security.protobuf.Security.EncryptionTransformation getTransformation() {
      @SuppressWarnings("deprecation")
      io.opencola.security.protobuf.Security.EncryptionTransformation result = io.opencola.security.protobuf.Security.EncryptionTransformation.valueOf(transformation_);
      return result == null ? io.opencola.security.protobuf.Security.EncryptionTransformation.UNRECOGNIZED : result;
    }

    public static final int BYTES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bytes_;
    /**
     * <code>bytes bytes = 2;</code>
     * @return The bytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (transformation_ != io.opencola.security.protobuf.Security.EncryptionTransformation.ECIES_WITH_AES_CBC.getNumber()) {
        output.writeEnum(1, transformation_);
      }
      if (!bytes_.isEmpty()) {
        output.writeBytes(2, bytes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (transformation_ != io.opencola.security.protobuf.Security.EncryptionTransformation.ECIES_WITH_AES_CBC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, transformation_);
      }
      if (!bytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.opencola.security.protobuf.Security.EncryptedBytes)) {
        return super.equals(obj);
      }
      io.opencola.security.protobuf.Security.EncryptedBytes other = (io.opencola.security.protobuf.Security.EncryptedBytes) obj;

      if (transformation_ != other.transformation_) return false;
      if (!getBytes()
          .equals(other.getBytes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRANSFORMATION_FIELD_NUMBER;
      hash = (53 * hash) + transformation_;
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.security.protobuf.Security.EncryptedBytes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.opencola.security.protobuf.Security.EncryptedBytes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.opencola.security.protobuf.EncryptedBytes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.opencola.security.protobuf.EncryptedBytes)
        io.opencola.security.protobuf.Security.EncryptedBytesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_EncryptedBytes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_EncryptedBytes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.opencola.security.protobuf.Security.EncryptedBytes.class, io.opencola.security.protobuf.Security.EncryptedBytes.Builder.class);
      }

      // Construct using io.opencola.security.protobuf.Security.EncryptedBytes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        transformation_ = 0;

        bytes_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.opencola.security.protobuf.Security.internal_static_io_opencola_security_protobuf_EncryptedBytes_descriptor;
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.EncryptedBytes getDefaultInstanceForType() {
        return io.opencola.security.protobuf.Security.EncryptedBytes.getDefaultInstance();
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.EncryptedBytes build() {
        io.opencola.security.protobuf.Security.EncryptedBytes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.opencola.security.protobuf.Security.EncryptedBytes buildPartial() {
        io.opencola.security.protobuf.Security.EncryptedBytes result = new io.opencola.security.protobuf.Security.EncryptedBytes(this);
        result.transformation_ = transformation_;
        result.bytes_ = bytes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.opencola.security.protobuf.Security.EncryptedBytes) {
          return mergeFrom((io.opencola.security.protobuf.Security.EncryptedBytes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.opencola.security.protobuf.Security.EncryptedBytes other) {
        if (other == io.opencola.security.protobuf.Security.EncryptedBytes.getDefaultInstance()) return this;
        if (other.transformation_ != 0) {
          setTransformationValue(other.getTransformationValue());
        }
        if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
          setBytes(other.getBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.opencola.security.protobuf.Security.EncryptedBytes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.opencola.security.protobuf.Security.EncryptedBytes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int transformation_ = 0;
      /**
       * <code>.io.opencola.security.protobuf.EncryptionTransformation transformation = 1;</code>
       * @return The enum numeric value on the wire for transformation.
       */
      @java.lang.Override public int getTransformationValue() {
        return transformation_;
      }
      /**
       * <code>.io.opencola.security.protobuf.EncryptionTransformation transformation = 1;</code>
       * @param value The enum numeric value on the wire for transformation to set.
       * @return This builder for chaining.
       */
      public Builder setTransformationValue(int value) {
        
        transformation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.io.opencola.security.protobuf.EncryptionTransformation transformation = 1;</code>
       * @return The transformation.
       */
      @java.lang.Override
      public io.opencola.security.protobuf.Security.EncryptionTransformation getTransformation() {
        @SuppressWarnings("deprecation")
        io.opencola.security.protobuf.Security.EncryptionTransformation result = io.opencola.security.protobuf.Security.EncryptionTransformation.valueOf(transformation_);
        return result == null ? io.opencola.security.protobuf.Security.EncryptionTransformation.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.opencola.security.protobuf.EncryptionTransformation transformation = 1;</code>
       * @param value The transformation to set.
       * @return This builder for chaining.
       */
      public Builder setTransformation(io.opencola.security.protobuf.Security.EncryptionTransformation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        transformation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.opencola.security.protobuf.EncryptionTransformation transformation = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransformation() {
        
        transformation_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes = 2;</code>
       * @return The bytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>bytes bytes = 2;</code>
       * @param value The bytes to set.
       * @return This builder for chaining.
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytes() {
        
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.opencola.security.protobuf.EncryptedBytes)
    }

    // @@protoc_insertion_point(class_scope:io.opencola.security.protobuf.EncryptedBytes)
    private static final io.opencola.security.protobuf.Security.EncryptedBytes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.opencola.security.protobuf.Security.EncryptedBytes();
    }

    public static io.opencola.security.protobuf.Security.EncryptedBytes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EncryptedBytes>
        PARSER = new com.google.protobuf.AbstractParser<EncryptedBytes>() {
      @java.lang.Override
      public EncryptedBytes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EncryptedBytes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EncryptedBytes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EncryptedBytes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.opencola.security.protobuf.Security.EncryptedBytes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_opencola_security_protobuf_PublicKey_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_opencola_security_protobuf_PublicKey_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_opencola_security_protobuf_Signature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_opencola_security_protobuf_Signature_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_opencola_security_protobuf_SignedBytes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_opencola_security_protobuf_SignedBytes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_opencola_security_protobuf_EncryptedBytes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_opencola_security_protobuf_EncryptedBytes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016security.proto\022\035io.opencola.security.p" +
      "rotobuf\"\034\n\tPublicKey\022\017\n\007encoded\030\001 \001(\014\"`\n" +
      "\tSignature\022D\n\talgorithm\030\001 \001(\01621.io.openc" +
      "ola.security.protobuf.SignatureAlgorithm" +
      "\022\r\n\005bytes\030\002 \001(\014\"Y\n\013SignedBytes\022;\n\tsignat" +
      "ure\030\001 \001(\0132(.io.opencola.security.protobu" +
      "f.Signature\022\r\n\005bytes\030\002 \001(\014\"p\n\016EncryptedB" +
      "ytes\022O\n\016transformation\030\001 \001(\01627.io.openco" +
      "la.security.protobuf.EncryptionTransform" +
      "ation\022\r\n\005bytes\030\002 \001(\014*-\n\022SignatureAlgorit" +
      "hm\022\027\n\023SHA3_256_WITH_ECDSA\020\000*2\n\030Encryptio" +
      "nTransformation\022\026\n\022ECIES_WITH_AES_CBC\020\000b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_opencola_security_protobuf_PublicKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_opencola_security_protobuf_PublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_opencola_security_protobuf_PublicKey_descriptor,
        new java.lang.String[] { "Encoded", });
    internal_static_io_opencola_security_protobuf_Signature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_opencola_security_protobuf_Signature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_opencola_security_protobuf_Signature_descriptor,
        new java.lang.String[] { "Algorithm", "Bytes", });
    internal_static_io_opencola_security_protobuf_SignedBytes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_opencola_security_protobuf_SignedBytes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_opencola_security_protobuf_SignedBytes_descriptor,
        new java.lang.String[] { "Signature", "Bytes", });
    internal_static_io_opencola_security_protobuf_EncryptedBytes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_opencola_security_protobuf_EncryptedBytes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_opencola_security_protobuf_EncryptedBytes_descriptor,
        new java.lang.String[] { "Transformation", "Bytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
