#!/bin/bash

OS="`uname`"
case $OS in
  'Darwin')
      sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain opencola-ssl.der
      ;;
  'Linux')
    # https://ubuntu.com/server/docs/security-trust-store
    # This doesn't seem to be working. Cert seems to be installed, but browser doesn't recognize it
    # sudo cp opencola-ssl.pem /usr/local/share/ca-certificates/opencola-ssl.crt
    # sudo update-ca-certificates # --fresh
    #
    # Manaul Install
      cp opencola-ssl.pem ~
      echo "A certificate has been placed at ~/opencola-ssl.pem"
      echo "***"
      echo "*** You must manually install it into your browser. ***"
      echo "***"
      echo "For Chome based browsers:"
      echo " 1. Open chrome://settings/certificates in your browser"
      echo "      (or brave://settings/certificates for Brave)"
      echo " 2. Select the 'Authorities' tab"
      echo " 3. Click the 'Import' button'"
      echo " 4. Select 'opencola-ssl.pem' from your home directory"
      echo " 5. Check 'Trust this certificate for identifying websites'"
      echo " 6. Click 'OK'"
      echo 
      ;;
   *)
   echo "Unknown OS - unable to install cer"
   ;;
esac
