#!/bin/bash

#
# Copyright 2024 OpenCola
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

OS="`uname`"
case $OS in
  'Darwin')
      security add-trusted-cert -k login.keychain-db opencola-ssl.pem
      ;;
  'Linux')
    # https://ubuntu.com/server/docs/security-trust-store
    # This doesn't seem to be working. Cert seems to be installed, but browser doesn't recognize it
    # sudo cp opencola-ssl.pem /usr/local/share/ca-certificates/opencola-ssl.crt
    # sudo update-ca-certificates # --fresh
    #
    # Manaul Install
      cp opencola-ssl.pem ~
      echo "A certificate has been placed at ~/opencola-ssl.pem"
      echo "***"
      echo "*** You must manually install it into your browser. ***"
      echo "***"
      echo "For Chome based browsers:"
      echo " 1. Open chrome://settings/certificates in your browser"
      echo "      (or brave://settings/certificates for Brave)"
      echo " 2. Select the 'Authorities' tab"
      echo " 3. Click the 'Import' button'"
      echo " 4. Select 'opencola-ssl.pem' from your home directory"
      echo " 5. Check 'Trust this certificate for identifying websites'"
      echo " 6. Click 'OK'"
      echo 
      ;;
   *)
   echo "Unknown OS - unable to install cer"
   ;;
esac
