# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Daily build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: read

jobs:
  build:
    name: Build oc-server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: install

    steps:
    
    #step: Checkout code
    - name: Checkout
      uses: actions/checkout@v3

    #step: Set up Java env
    - name: Build
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
    
    #step: Build
    - name: Build with install script
      run: |
        ./install
    #    rm *.tgz

    #step: get the date for the build packages
    - name: Get date for build outputs
      id: date
      run: echo "date_string=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
      
    #step: upload build
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: oc_${{ env.date_string }}Z_${{ github.REF_NAME }}_${{ github.RUN_ID }}-${{ github.RUN_ATTEMPT }}
        path: install/
        retention-days: 3
