// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: util.proto

package io.opencola.util.protobuf;

public final class Util {
  private Util() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code io.opencola.util.protobuf.CompressionFormat}
   */
  public enum CompressionFormat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>DEFLATE = 1;</code>
     */
    DEFLATE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>DEFLATE = 1;</code>
     */
    public static final int DEFLATE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CompressionFormat valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CompressionFormat forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return DEFLATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CompressionFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CompressionFormat> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CompressionFormat>() {
            public CompressionFormat findValueByNumber(int number) {
              return CompressionFormat.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.opencola.util.protobuf.Util.getDescriptor().getEnumTypes().get(0);
    }

    private static final CompressionFormat[] VALUES = values();

    public static CompressionFormat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CompressionFormat(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.opencola.util.protobuf.CompressionFormat)
  }

  public interface CompressedBytesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.opencola.util.protobuf.CompressedBytes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.io.opencola.util.protobuf.CompressionFormat format = 1;</code>
     * @return The enum numeric value on the wire for format.
     */
    int getFormatValue();
    /**
     * <code>.io.opencola.util.protobuf.CompressionFormat format = 1;</code>
     * @return The format.
     */
    io.opencola.util.protobuf.Util.CompressionFormat getFormat();

    /**
     * <code>bytes bytes = 2;</code>
     * @return The bytes.
     */
    com.google.protobuf.ByteString getBytes();
  }
  /**
   * Protobuf type {@code io.opencola.util.protobuf.CompressedBytes}
   */
  public static final class CompressedBytes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.opencola.util.protobuf.CompressedBytes)
      CompressedBytesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CompressedBytes.newBuilder() to construct.
    private CompressedBytes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CompressedBytes() {
      format_ = 0;
      bytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CompressedBytes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opencola.util.protobuf.Util.internal_static_io_opencola_util_protobuf_CompressedBytes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opencola.util.protobuf.Util.internal_static_io_opencola_util_protobuf_CompressedBytes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opencola.util.protobuf.Util.CompressedBytes.class, io.opencola.util.protobuf.Util.CompressedBytes.Builder.class);
    }

    public static final int FORMAT_FIELD_NUMBER = 1;
    private int format_ = 0;
    /**
     * <code>.io.opencola.util.protobuf.CompressionFormat format = 1;</code>
     * @return The enum numeric value on the wire for format.
     */
    @java.lang.Override public int getFormatValue() {
      return format_;
    }
    /**
     * <code>.io.opencola.util.protobuf.CompressionFormat format = 1;</code>
     * @return The format.
     */
    @java.lang.Override public io.opencola.util.protobuf.Util.CompressionFormat getFormat() {
      io.opencola.util.protobuf.Util.CompressionFormat result = io.opencola.util.protobuf.Util.CompressionFormat.forNumber(format_);
      return result == null ? io.opencola.util.protobuf.Util.CompressionFormat.UNRECOGNIZED : result;
    }

    public static final int BYTES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes = 2;</code>
     * @return The bytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (format_ != io.opencola.util.protobuf.Util.CompressionFormat.NONE.getNumber()) {
        output.writeEnum(1, format_);
      }
      if (!bytes_.isEmpty()) {
        output.writeBytes(2, bytes_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (format_ != io.opencola.util.protobuf.Util.CompressionFormat.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, format_);
      }
      if (!bytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bytes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.opencola.util.protobuf.Util.CompressedBytes)) {
        return super.equals(obj);
      }
      io.opencola.util.protobuf.Util.CompressedBytes other = (io.opencola.util.protobuf.Util.CompressedBytes) obj;

      if (format_ != other.format_) return false;
      if (!getBytes()
          .equals(other.getBytes())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + format_;
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytes().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.opencola.util.protobuf.Util.CompressedBytes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.opencola.util.protobuf.Util.CompressedBytes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.opencola.util.protobuf.CompressedBytes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.opencola.util.protobuf.CompressedBytes)
        io.opencola.util.protobuf.Util.CompressedBytesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.opencola.util.protobuf.Util.internal_static_io_opencola_util_protobuf_CompressedBytes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.opencola.util.protobuf.Util.internal_static_io_opencola_util_protobuf_CompressedBytes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.opencola.util.protobuf.Util.CompressedBytes.class, io.opencola.util.protobuf.Util.CompressedBytes.Builder.class);
      }

      // Construct using io.opencola.util.protobuf.Util.CompressedBytes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        format_ = 0;
        bytes_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.opencola.util.protobuf.Util.internal_static_io_opencola_util_protobuf_CompressedBytes_descriptor;
      }

      @java.lang.Override
      public io.opencola.util.protobuf.Util.CompressedBytes getDefaultInstanceForType() {
        return io.opencola.util.protobuf.Util.CompressedBytes.getDefaultInstance();
      }

      @java.lang.Override
      public io.opencola.util.protobuf.Util.CompressedBytes build() {
        io.opencola.util.protobuf.Util.CompressedBytes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.opencola.util.protobuf.Util.CompressedBytes buildPartial() {
        io.opencola.util.protobuf.Util.CompressedBytes result = new io.opencola.util.protobuf.Util.CompressedBytes(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.opencola.util.protobuf.Util.CompressedBytes result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.format_ = format_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bytes_ = bytes_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.opencola.util.protobuf.Util.CompressedBytes) {
          return mergeFrom((io.opencola.util.protobuf.Util.CompressedBytes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.opencola.util.protobuf.Util.CompressedBytes other) {
        if (other == io.opencola.util.protobuf.Util.CompressedBytes.getDefaultInstance()) return this;
        if (other.format_ != 0) {
          setFormatValue(other.getFormatValue());
        }
        if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
          setBytes(other.getBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                format_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                bytes_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int format_ = 0;
      /**
       * <code>.io.opencola.util.protobuf.CompressionFormat format = 1;</code>
       * @return The enum numeric value on the wire for format.
       */
      @java.lang.Override public int getFormatValue() {
        return format_;
      }
      /**
       * <code>.io.opencola.util.protobuf.CompressionFormat format = 1;</code>
       * @param value The enum numeric value on the wire for format to set.
       * @return This builder for chaining.
       */
      public Builder setFormatValue(int value) {
        format_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.io.opencola.util.protobuf.CompressionFormat format = 1;</code>
       * @return The format.
       */
      @java.lang.Override
      public io.opencola.util.protobuf.Util.CompressionFormat getFormat() {
        io.opencola.util.protobuf.Util.CompressionFormat result = io.opencola.util.protobuf.Util.CompressionFormat.forNumber(format_);
        return result == null ? io.opencola.util.protobuf.Util.CompressionFormat.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.opencola.util.protobuf.CompressionFormat format = 1;</code>
       * @param value The format to set.
       * @return This builder for chaining.
       */
      public Builder setFormat(io.opencola.util.protobuf.Util.CompressionFormat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        format_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.opencola.util.protobuf.CompressionFormat format = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        format_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes = 2;</code>
       * @return The bytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>bytes bytes = 2;</code>
       * @param value The bytes to set.
       * @return This builder for chaining.
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        bytes_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.opencola.util.protobuf.CompressedBytes)
    }

    // @@protoc_insertion_point(class_scope:io.opencola.util.protobuf.CompressedBytes)
    private static final io.opencola.util.protobuf.Util.CompressedBytes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.opencola.util.protobuf.Util.CompressedBytes();
    }

    public static io.opencola.util.protobuf.Util.CompressedBytes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompressedBytes>
        PARSER = new com.google.protobuf.AbstractParser<CompressedBytes>() {
      @java.lang.Override
      public CompressedBytes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CompressedBytes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompressedBytes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.opencola.util.protobuf.Util.CompressedBytes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_opencola_util_protobuf_CompressedBytes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_opencola_util_protobuf_CompressedBytes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nutil.proto\022\031io.opencola.util.protobuf\"" +
      "^\n\017CompressedBytes\022<\n\006format\030\001 \001(\0162,.io." +
      "opencola.util.protobuf.CompressionFormat" +
      "\022\r\n\005bytes\030\002 \001(\014**\n\021CompressionFormat\022\010\n\004" +
      "NONE\020\000\022\013\n\007DEFLATE\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_opencola_util_protobuf_CompressedBytes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_opencola_util_protobuf_CompressedBytes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_opencola_util_protobuf_CompressedBytes_descriptor,
        new java.lang.String[] { "Format", "Bytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
